package view;


import java.awt.Desktop;
import java.awt.Image;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hasan
 */
public class HesapAlani extends javax.swing.JFrame {
private String kadi,adi,soyadi,email;
private int aracCarpani,yasCarpani,modelCarpani,kazaCarpani,depremCarpani,hastalikCarpani,hyCarpani;
    public JLabel getAd_alani() {
        return ad_alani;
    }

    public void setAd_alani(JLabel ad_alani) {
        this.ad_alani = ad_alani;
    }

    public JButton getBilgileri_goster() {
        return bilgileri_goster;
    }

    public void setBilgileri_goster(JButton bilgileri_goster) {
        this.bilgileri_goster = bilgileri_goster;
    }

    public JLabel getEmail_alani() {
        return email_alani;
    }

    public void setEmail_alani(JLabel email_alani) {
        this.email_alani = email_alani;
    }

    public JLabel getKullanici_adi_alani() {
        return kullanici_adi_alani;
    }

    public void setKullanici_adi_alani(JLabel kullanici_adi_alani) {
        this.kullanici_adi_alani = kullanici_adi_alani;
    }

    public JLabel getSoyad_alani() {
        return soyad_alani;
    }

    public void setSoyad_alani(JLabel soyad_alani) {
        this.soyad_alani = soyad_alani;
    }
    
    

    /**
     * Creates new form HesapAlani
     */
    public HesapAlani(String kadi,String adi,String soyadi,String email) {
        initComponents();
        this.kadi=kadi;
        this.adi=adi;
        this.soyadi=soyadi;
        this.email=email;
        this.kullanici_adi_alani.setText(kadi);
        this.ad_alani.setText(adi);
        this.soyad_alani.setText(soyadi);
        this.email_alani.setText(email);
        
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kullanici_adi_alani = new javax.swing.JLabel();
        ad_alani = new javax.swing.JLabel();
        soyad_alani = new javax.swing.JLabel();
        email_alani = new javax.swing.JLabel();
        bilgileri_goster = new javax.swing.JButton();
        cikis_butonu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        sigorta_turu = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        yas_secim = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        twitter_butonu = new javax.swing.JButton();
        facebook_butonu = new javax.swing.JButton();
        instagram_butonu = new javax.swing.JButton();
        hakkimizda_butonu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HESAPLAMA ALANI");
        setBounds(new java.awt.Rectangle(400, 400, 0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));

        jLabel1.setText("Kullanıcı Adı : ");

        jLabel2.setText("Ad : ");

        jLabel3.setText("SoyAd :");

        jLabel4.setText("Email Adresi : ");

        bilgileri_goster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconfinder_preferences-desktop-user_8806.png"))); // NOI18N
        bilgileri_goster.setText("Bilgileri Göster");
        bilgileri_goster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilgileri_gosterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(kullanici_adi_alani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(ad_alani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(soyad_alani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(25, 25, 25)
                        .addComponent(email_alani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bilgileri_goster)
                        .addGap(0, 102, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(kullanici_adi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(ad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(soyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(email_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bilgileri_goster)
                .addContainerGap())
        );

        cikis_butonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconfinder_exit_38999.png"))); // NOI18N
        cikis_butonu.setText("Çıkış Yap");
        cikis_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikis_butonuActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconfinder_Finance_finance_calculator_1889192.png"))); // NOI18N
        jButton1.setText("Hesapla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        sigorta_turu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEÇİNİZ : ", "ARAÇ", "SAĞLIK", "DEPREM" }));
        sigorta_turu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigorta_turuActionPerformed(evt);
            }
        });

        jLabel8.setText("YAŞ :");

        yas_secim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEÇİNİZ : ", "1-5", "6-10", "10+", " " }));

        jLabel9.setText("MODEL");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEDAN", "TİCARİ", "HATCBACK" }));

        jLabel10.setText("KAZA");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VAR", "YOK" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sigorta_turu, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yas_secim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sigorta_turu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(yas_secim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ARAÇ", jPanel5);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("SAĞLIK", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("DEPREM", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconfinder_arrow-down-right_59810.png"))); // NOI18N
        jLabel7.setText("Sosyal Medya Adreslerimiz : ");

        twitter_butonu.setBackground(new java.awt.Color(0, 0, 153));
        twitter_butonu.setForeground(new java.awt.Color(51, 0, 51));
        twitter_butonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconfinder_twitter_312527.png"))); // NOI18N
        twitter_butonu.setText("Twitter");
        twitter_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twitter_butonuActionPerformed(evt);
            }
        });

        facebook_butonu.setBackground(new java.awt.Color(51, 51, 255));
        facebook_butonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconfinder_facebook_295880 (1).png"))); // NOI18N
        facebook_butonu.setText("Facebook");
        facebook_butonu.setMaximumSize(new java.awt.Dimension(189, 115));
        facebook_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facebook_butonuActionPerformed(evt);
            }
        });

        instagram_butonu.setBackground(new java.awt.Color(255, 102, 102));
        instagram_butonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconfinder_social-media_instagram_1543322.png"))); // NOI18N
        instagram_butonu.setText("Instagram");
        instagram_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instagram_butonuActionPerformed(evt);
            }
        });

        hakkimizda_butonu.setText("Hakkımızda");
        hakkimizda_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hakkimizda_butonuActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("SÜLEYMAN DEMİREL ÜNİVERSİTESİ\nBİLGİSAYAR MÜHENDİSLİĞİ BÖLÜMÜ\nYAZILIM MÜHENDİSLİĞİ DERSİ\nDÖNEM ÖDEVİ İÇİN HAZIRLANMIŞ\nBİR PROJEDİR. HİÇ BİR TİCARİ\nAMACI BULUNMAMAKTADIR.\nEĞER SORUN TEŞKİL EDEN DURUM\nSÖZ KONUSU OLDUYSA VEYA\nPROGRAMIN GELİŞTİRİLMESİ İÇİN\nÖNERİNİZ VARSA LÜTFEN SOSYAL\nMEDYA ADRESLERİMİZE VEYA \nASKURUCU ÜYEMİZ OLAN \nHASAN ALİ YILDIR'IN\n EMAİL ADRESİ \nOLAN tinim123@gmail.com ADRESİNE \nYAZINIZ. GÖRÜŞ VE ÖNERİLERİNİZ\nBİZİM İÇİN ÖNEMLİDİR.\n\nKURUCU ÜYELER : \nAYŞE İPEK YILMAZ\nHASAN ALİ YILDIR\nÖZLEM YILMAZ\nKENAN YILMAZ\nNEVİN İN ");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hakkimizda_butonu)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(instagram_butonu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(facebook_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(twitter_butonu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cikis_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(facebook_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twitter_butonu)
                            .addComponent(cikis_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(instagram_butonu))
                        .addGap(46, 46, 46)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hakkimizda_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cikis_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikis_butonuActionPerformed
       JOptionPane.showMessageDialog(this, "Çıkış Yapılıyor. BIGGANG SİGORTA A.Ş Olarak İyi Günler Dileriz.");
       System.exit(0);
    }//GEN-LAST:event_cikis_butonuActionPerformed

    private void bilgileri_gosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilgileri_gosterActionPerformed
        
    }//GEN-LAST:event_bilgileri_gosterActionPerformed

    private void hakkimizda_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hakkimizda_butonuActionPerformed
      new Hakkimizda().show();
      //hakkimizda.setVisible(true);
    }//GEN-LAST:event_hakkimizda_butonuActionPerformed

    private void sigorta_turuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigorta_turuActionPerformed
       
    }//GEN-LAST:event_sigorta_turuActionPerformed

    private void instagram_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instagram_butonuActionPerformed
      String internet="https://www.instagram.com/biggangsigorta/";
      Desktop d=Desktop.getDesktop();
        try {
            d.browse(new URI(internet));
        } catch (IOException ex) {
            Logger.getLogger(HesapAlani.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(HesapAlani.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_instagram_butonuActionPerformed

    private void facebook_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facebook_butonuActionPerformed
      String internet="https://www.facebook.com/B%C4%B0G-GANG-Sigorta-448369702565849/?modal=admin_todo_tour";
      Desktop d=Desktop.getDesktop();
        try {
            d.browse(new URI(internet));
        } catch (IOException ex) {
            Logger.getLogger(HesapAlani.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(HesapAlani.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_facebook_butonuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if(sigorta_turu.getSelectedItem().equals("ARAÇ")){
    this.aracCarpani=1;
    }
    if(sigorta_turu.getSelectedItem().toString().equals("DEPREM")){
    this.depremCarpani=1;
    }
    if(sigorta_turu.getSelectedItem().toString().equals("SAĞLIK")){
    this.hastalikCarpani=1;
    }


    if(this.yas_secim.getSelectedItem().toString().equals("1-5")){
    this.yasCarpani=100;
    }
    if(this.yas_secim.getSelectedItem().toString().equals("6-10")){
    this.yasCarpani=200;
    }    
    if(this.yas_secim.getSelectedItem().toString().equals("10+")){
    this.yasCarpani=300;
    }  

    if(this.jComboBox1.getSelectedItem().toString().equals("SEDAN")){
    this.modelCarpani=100;
    }  
    if(this.jComboBox1.getSelectedItem().toString().equals("HATCBACK")){
    this.modelCarpani=50;
    }      
    if(this.jComboBox1.getSelectedItem().toString().equals("TİCARİ")){
    this.modelCarpani=300;
    }  
    
    if(this.jComboBox2.getSelectedItem().toString().equals("VAR")){
    this.kazaCarpani=500;
    }      
     if(this.jComboBox2.getSelectedItem().toString().equals("YOK")){
    this.kazaCarpani=10;
    }  
     
    this.jTextArea1.setText(Integer.toString(this.aracCarpani+this.yasCarpani+this.modelCarpani+this.kazaCarpani+100)+" TL ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void twitter_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twitter_butonuActionPerformed
        String internet="https://twitter.com/BiggangSigorta";
        Desktop d=Desktop.getDesktop();
        try {
            d.browse(new URI(internet));
        } catch (IOException ex) {
            Logger.getLogger(HesapAlani.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(HesapAlani.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_twitter_butonuActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ad_alani;
    private javax.swing.JButton bilgileri_goster;
    private javax.swing.JButton cikis_butonu;
    private javax.swing.JLabel email_alani;
    private javax.swing.JButton facebook_butonu;
    private javax.swing.JButton hakkimizda_butonu;
    private javax.swing.JButton instagram_butonu;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel kullanici_adi_alani;
    private javax.swing.JComboBox sigorta_turu;
    private javax.swing.JLabel soyad_alani;
    private javax.swing.JButton twitter_butonu;
    private javax.swing.JComboBox yas_secim;
    // End of variables declaration//GEN-END:variables
}
